/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class adamKraft_videoUtils_MovieReader */

#ifndef _Included_adamKraft_videoUtils_MovieReader
#define _Included_adamKraft_videoUtils_MovieReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     adamKraft_videoUtils_MovieReader
 * Method:    nativeGetNextFrame
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_adamKraft_videoUtils_MovieReader_nativeGetNextFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     adamKraft_videoUtils_MovieReader
 * Method:    nativePrefetchFrame
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_adamKraft_videoUtils_MovieReader_nativePrefetchFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     adamKraft_videoUtils_MovieReader
 * Method:    nativeSkipFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_adamKraft_videoUtils_MovieReader_nativeSkipFrame
  (JNIEnv *, jobject, jint);
  
/*
 * Class:     adamKraft_videoUtils_MovieReader
 * Method:    nativeSeekToFrame
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_adamKraft_videoUtils_MovieReader_nativeSeekToFrame
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     adamKraft_videoUtils_MovieReader
 * Method:    nativeCaptureAllocate
 * Signature: (ILjava/lang/String;ZI)V
 */
JNIEXPORT void JNICALL Java_adamKraft_videoUtils_MovieReader_nativeCaptureAllocate
  (JNIEnv *, jobject, jint, jstring, jboolean, jint);

/*
 * Class:     adamKraft_videoUtils_MovieReader
 * Method:    nativeCaptureFree
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_adamKraft_videoUtils_MovieReader_nativeCaptureFree
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
