/*  1:   */ package constants;
/*  2:   */ 
/*  3:   */ import bridge.reps.entities.Entity;
/*  4:   */ 
/*  5:   */ public class Markers
/*  6:   */ {
/*  7:   */   public static final String DESCRIPTOR = "ad_word";
/*  8:   */   public static final String SOMEONE = "someone";
/*  9:   */   public static final String ANYONE = "anyone";
/* 10:   */   public static final String PEOPLE = "people";
/* 11:   */   public static final String SOMETHING = "something";
/* 12:   */   public static final String YOU = "you";
/* 13:   */   public static final String BELIEVE = "believe";
/* 14:   */   public static final String I = "I";
/* 15:   */   public static final String i = "i";
/* 16:   */   public static final String IAM = "I am";
/* 17:35 */   public static final Entity NULL = new Entity("null");
/* 18:   */   public static final String IS_QUESTION_MARKER = "is_question";
/* 19:   */   public static final String QUESTION_MARKER = "question";
/* 20:   */   public static final String IMPERATIVE = "imperative";
/* 21:   */   public static final String DESCRIBE_MARKER = "description";
/* 22:   */   public static final String MEANING_RESTRICTION = "mean";
/* 23:   */   public static final String ASSUME = "assume";
/* 24:   */   public static final String ASSUMPTION = "assumption";
/* 25:   */   public static final String PAUSE_MARKER = "pause";
/* 26:   */   public static final String PERSUATION_MARKER = "persuade";
/* 27:   */   public static final String ASK_MARKER = "ask";
/* 28:   */   public static final String INTENTION_MARKER = "intend";
/* 29:   */   public static final String STORY_MARKER = "story";
/* 30:   */   public static final String VIDEO_MARKER = "video";
/* 31:   */   public static final String PRECEDENT_MARKER = "precedent";
/* 32:   */   public static final String REMEMBER_MARKER = "remember";
/* 33:   */   public static final String CLUSTER_MARKER = "cluster";
/* 34:   */   public static final String PATTERN_ALIGNER_MARKER = "align";
/* 35:   */   public static final String CONCEPT_MARKER = "reflection";
/* 36:   */   public static final String COMMAND_MARKER = "command";
/* 37:   */   public static final String BELIEF_MARKER = "believes-event";
/* 38:   */   public static final String CAUSE_MARKER = "cause";
/* 39:   */   public static final String IF_MARKER = "if";
/* 40:   */   public static final String ONSET_MARKER = "onset";
/* 41:   */   public static final String INDICATORS = "indicators";
/* 42:   */   public static final String INDICATIONS = "indications";
/* 43:   */   public static final String FORCE_MARKER = "force";
/* 44:   */   public static final String MOVE_MARKER = "move";
/* 45:   */   public static final String ENTAIL_MARKER = "entail";
/* 46:   */   public static final String EQUAL_MARKER = "equal";
/* 47:   */   public static final String TRY_MARKER = "try";
/* 48:   */   public static final String BODY_PART_WORD = "have";
/* 49:   */   public static final String TIME_MARKER = "time-relation";
/* 50:   */   public static final String TRAJECTORY_MARKER = "travel";
/* 51:   */   public static final String PATH_MARKER = "path";
/* 52:   */   public static final String PATH_ELEMENT_MARKER = "path-element";
/* 53:   */   public static final String PLACE_MARKER = "place";
/* 54:   */   public static final String OWNER_MARKER = "owner";
/* 55:   */   public static final String TRANSITION_MARKER = "transition";
/* 56:   */   public static final String TRANSFER_MARKER = "transfer";
/* 57:   */   public static final String GOAL_MARKER = "goal";
/* 58:   */   public static final String HELP_MARKER = "help";
/* 59:   */   public static final String HARM_MARKER = "harm";
/* 60:   */   public static final String PREPARE_MARKER = "prepare";
/* 61:   */   public static final String WANT_MARKER = "want";
/* 62:   */   public static final String DESIRE_MARKER = "desire";
/* 63:   */   public static final String SOCIAL_MARKER = "social relation";
/* 64:   */   public static final String RELATIVE = "relative";
/* 65:   */   public static final String PLACE_TYPE = "location";
/* 66:   */   public static final String SEMANTIC_INTERPRETATION = "semantic-interpretation";
/* 67:   */   public static final String CHAIN = "chain";
/* 68:   */   public static final String NEXT = "next";
/* 69:   */   public static final String PATH = "path";
/* 70:   */   public static final String LOOP = "loop";
/* 71:   */   public static final String DIRECT = "direct";
/* 72:   */   public static final String VIEWER = "viewer";
/* 73:   */   public static final String TEXT = "text";
/* 74:   */   public static final String BECAUSE = "because";
/* 75:   */   public static final String LEADS_TO = "leads_to";
/* 76:   */   public static final String BECOME = "become";
/* 77:   */   public static final String TIME_TYPE = "time-relation";
/* 78:   */   public static final String STATE_TYPE = "state";
/* 79:   */   public static final String JOB_TYPE_MARKER = "position";
/* 80:   */   public static final String COMPARISON_MARKER = "comparison";
/* 81:   */   public static final String PROPERTY_TYPE = "property";
/* 82:   */   public static final String POSITION_TYPE = "position";
/* 83:   */   public static final String LOCATION_TYPE = "location";
/* 84:   */   public static final String PERSONALITY_TRAIT = "personality_trait";
/* 85:   */   public static final String PERSONALITY_TYPE = "personality_type";
/* 86:   */   public static final String THREAD_TYPE = "type";
/* 87:   */   public static final String CLASSIFICATION_MARKER = "classification";
/* 88:   */   public static final String CHARACTER = "character";
/* 89:   */   public static final String COERCE_MARKER = "induce";
/* 90:   */   public static final String QUESTION = "question";
/* 91:   */   public static final String IMAGINE = "imagine";
/* 92:   */   public static final String MAKE = "make";
/* 93:   */   public static final String POSITIVE = "happy";
/* 94:   */   public static final String NEGATIVE = "unhappy";
/* 95:   */   public static final String ANGRY = "angry";
/* 96:   */   public static final String POSITIVE_VIEW = "viewsAsPositive";
/* 97:   */   public static final String NEGATIVE_VIEW = "viewsAsNegative";
/* 98:   */   public static final String THE_END = "theEnd";
/* 99:   */   public static final String REPLAY = "replayStory";
/* :0:   */   public static final String RADIATE_COMMONSENSE = "radiateRules";
/* :1:   */   public static final String INSERT_BIAS = "insertBias";
/* :2:   */   public static final String CONJUNCTION = "conjuction";
/* :3:   */   public static final String PREDICTION = "prediction";
/* :4:   */   public static final String EXPECTATION = "expectation";
/* :5:   */   public static final String ENABLER = "enabler";
/* :6:   */   public static final String INTENTION = "intension";
/* :7:   */   public static final String EXPLANATION = "explanation";
/* :8:   */   public static final String PROXIMITY = "proximity";
/* :9:   */   public static final String ABDUCTION = "abduction";
/* ;0:   */   public static final String CENSOR = "censor";
/* ;1:   */   public static final String INFERENCE_MARKER = "inference";
/* ;2:   */   public static final String CERTAINTY = "certainty";
/* ;3:   */   public static final String TENTATIVE = "tentative";
/* ;4:   */   public static final String MAY_WORD = "may";
/* ;5:   */   public static final String MUST_WORD = "must";
/* ;6:   */   public static final String MODAL = "modal";
/* ;7:   */   public static final String PERFECTIVE = "perfective";
/* ;8:   */   public static final String TENSE = "tense";
/* ;9:   */   public static final String PROGRESSIVE = "progressive";
/* <0:   */   public static final String QUANTITY = "quantity";
/* <1:   */   public static final String WILL_WORD = "will";
/* <2:   */   public static final String LIKE_WORD = "like";
/* <3:   */   public static final String ACTION_WORD = "action";
/* <4:   */   public static final String ENTITY_WORD = "entity";
/* <5:   */   public static final String POSSESSIVE_WORD = "of";
/* <6:   */   public static final String FEATURE = "feature";
/* <7:   */   public static final String DETERMINER = "determiner";
/* <8:   */   public static final String DEFINITE = "definite";
/* <9:   */   public static final String INDEFINITE = "indefinite";
/* =0:   */   public static final String NONE = "none";
/* =1:   */   public static final String ANOTHER = "another";
/* =2:   */   public static final String FIRST = "first";
/* =3:   */   public static final String SECOND = "second";
/* =4:   */   public static final String THIRD = "third";
/* =5:   */   public static final String FOURTH = "fourth";
/* =6:   */   public static final String FIFTH = "fifth";
/* =7:   */   public static final String NOT = "not";
/* =8:   */   public static final String CAN = "can";
/* =9:   */   public static final String HAVE = "have";
/* >0:   */   public static final String CONCEPT = "concept-related";
/* >1:   */   public static final String BODY_PART_MARKER = "has-body-part";
/* >2:   */   public static final String PART_OF = "has-part";
/* >3:   */   public static final String STORY_START_WORD = "start";
/* >4:   */   public static final String CHECK_WORD = "check";
/* >5:   */   public static final String APPEAR_MARKER = "appear";
/* >6:   */   public static final String DISAPPEAR_MARKER = "disappear";
/* >7:   */   public static final String INCREASE = "increase";
/* >8:   */   public static final String DECREASE = "decrease";
/* >9:   */   public static final String CHANGE = "change";
/* ?0:   */   public static final String PROCESSED = "processed";
/* ?1:   */   public static final String THE_END_TEXT = "The end";
/* ?2:   */   public static final String REPLAY_TEXT = "Replay story";
/* ?3:   */   public static final String RADIATE_COMMONSENSE_TEXT = "Radiate commonsense knowledge";
/* ?4:   */   public static final String INSERT_BIAS_TEXT = "Insert bias";
/* ?5:   */   public static final String FIRST_PERSPECTIVE_TEXT = "First perspective";
/* ?6:   */   public static final String SECOND_PERSPECTIVE_TEXT = "Second perspective";
/* ?7:   */   public static final String BOTH_PERSPECTIVES_TEXT = "Both perspectives";
/* ?8:   */   public static final String NEITHER_PERSPECTIVE_TEXT = "Neither perspective";
/* ?9:   */   public static final String SHOW_FIRST_PERSPECTIVE = "Show first perspective";
/* @0:   */   public static final String SHOW_SECOND_PERSPECTIVE = "Show second perspective";
/* @1:   */   public static final String SHOW_BOTH_PERSPECTIVES = "Show both perspectives";
/* @2:   */   public static final String START_EXPERIMENT = "Start experiment";
/* @3:   */   public static final String START_STORY_TEXT = "Start story titled";
/* @4:   */   public static final String INSERT_TEXT = "Insert into text box";
/* @5:   */   public static final String START_CONCEPT_TEXT = "Start description of";
/* @6:   */   public static final String SWITCH_TO_CONCEPT_REPORTING = "Start reflective knowledge";
/* @7:   */   public static final String SWITCH_TO_COMMONSENSE_REPORTING = "Start commonsense knowledge";
/* @8:   */   public static final String START_GENERAL_KNOWLEDGE_TEXT = "Start general knowledge";
/* @9:   */   public static final String CLEAR_STORY_MEMORY_TEXT = "Clear story memory";
/* A0:   */   public static final String CLEAR_EXPLANATORY_TEXT = "Clear explanatory text";
/* A1:   */   public static final String CLEAR_MENTAL_MODELS = "Clear mental models";
/* A2:   */   public static final String PAUSE_TEXT = "Pause";
/* A3:   */   public static final String ASSUMED = "assumption";
/* A4:   */   public static final String MILESTONE = "milestone";
/* A5:   */   public static final String THEN = "then";
/* A6:   */   public static final String SCENE = "scene";
/* A7:   */   public static final String PERSONA_MARKER = "Load persona";
/* A8:   */   public static final String NAME = "name";
/* A9:   */   public static final String PROPER = "proper";
/* B0:   */   public static final String TITLE = "title";
/* B1:   */   public static final String CALLED = "is_called";
/* B2:   */   public static final String RELATED_TO = "related-to";
/* B3:   */   public static final String THIS = "this";
/* B4:   */   public static final String UNKNOWN = "unknown";
/* B5:   */   public static final String RESET = "reset";
/* B6:   */   public static final String RESET_CONCEPT_NOTES = "reset concept notes";
/* B7:   */   public static final String DID_QUESTION = "did";
/* B8:   */   public static final String WHO_QUESTION = "who";
/* B9:   */   public static final String WHAT_QUESTION = "what";
/* C0:   */   public static final String WHY_QUESTION = "why";
/* C1:   */   public static final String WHERE_QUESTION = "where";
/* C2:   */   public static final String WHEN_QUESTION = "when";
/* C3:   */   public static final String WHETHER_QUESTION = "whether";
/* C4:   */   public static final String WHAT_HAPPENS_WHEN_QUESTION = "what happens when";
/* C5:   */   public static final String WHAT_IF_QUESTION = "what_if";
/* C6:   */   public static final String ACTION_MARKER = "action";
/* C7:   */   public static final String MAIN_MARKER = "is_main";
/* C8:   */   public static final String RELATIVE_MARKER = "has_rel_clause";
/* C9:   */   public static final String ROLE_MARKER = "roles";
/* D0:   */   public static final String AGENT_MARKER = "agent";
/* D1:   */   public static final String OBJECT_MARKER = "object";
/* D2:   */   public static final String TO_MARKER = "to";
/* D3:   */   public static final String FROM_MARKER = "from";
/* D4:   */   public static final String WITH_MARKER = "with";
/* D5:   */   public static final String FOR_MARKER = "for";
/* D6:   */   public static final String CLAUSES = "clauses";
/* D7:   */   public static final String CLAUSE_HOLDERS = "clause_holders";
/* D8:   */   public static final String YES = "yes";
/* D9:   */   public static final String IS_PROPER = "is_proper";
/* E0:   */   public static final String IS = "is";
/* E1:   */   public static final String IS_A = "is-a";
/* E2:   */   public static final String GERUND_OF = "gerund_of";
/* E3:   */   public static final String VERB_ROOT = "verb_root";
/* E4:   */   public static final String IS_PERFECTIVE = "is_perfective";
/* E5:   */   public static final String HAS_DETERMINER = "has_det";
/* E6:   */   public static final String HAS_MODIFIER = "has_modifier";
/* E7:   */   public static final String HAS_INTENSIFIER = "has_intensifier";
/* E8:   */   public static final String HAS_PURPOSE = "has_purpose";
/* E9:   */   public static final String MEANS = "means";
/* F0:   */   public static final String RECIPE = "recipe";
/* F1:   */   public static final String PERFORM = "perform";
/* F2:   */   public static final String CONCEPT_ANALYSIS_TAB = "Concept analysis";
/* F3:   */   public static final String PERSONALITY_ANALYSIS_TAB = "Personality analysis";
/* F4:   */   public static final String ANSWERS_TAB = "Answers";
/* F5:   */   public static final String POSSIBLY = "possibly";
/* F6:   */   public static final String AT = "at";
/* F7:   */   public static final String ON = "on";
/* F8:   */   public static final String IN = "in";
/* F9:   */   public static final String FROM = "from";
/* G0:   */   public static final String BY = "by";
/* G1:   */   public static final String TO = "to";
/* G2:   */   public static final String PAST = "past";
/* G3:   */   public static final String PRESENT = "present";
/* G4:   */   public static final String FUTURE = "future";
/* G5:   */   public static final String MENTAL_STATE_MARKER = "has-mental-state";
/* G6:   */   public static final String MENTAL_STATE = "mental-state";
/* G7:   */   public static final String MENTAL_MODEL = "mental-model";
/* G8:   */   public static final String MENTAL_MODEL_HOST = "mental-model-host";
/* G9:   */   public static final String IDIOM = "idiom";
/* H0:   */   public static final String SOMETIMES = "sometimes";
/* H1:   */   public static final String CHECK = "check";
/* H2:   */   public static final String INSERT_FILE = "Insert file ";
/* H3:   */   public static final String INSERT_START_EXPEREMENT_FILE = "Insert file Start experiment";
/* H4:   */   public static final String RUN_EXPERIMENTS = "Run what-if experiments ";
/* H5:   */   public static final String CONDITION_ON_EXPERIMENT = "Assume if experiment ";
/* H6:   */   public static final String TRAIT_EVENT_PREDICTION_MARKER = "predict";
/* H7:   */   public static final String START_NAMING_PREFIX = "Note that";
/* H8:   */   public static final String START_NAMING_SUFFIX = "is a name";
/* H9:   */   public static final String CHARACTERIZED = "characterized";
/* I0:   */   public static final String ALERT = "alert";
/* I1:   */   public static final String TRACK = "track";
/* I2:   */   public static final String ENABLE_WORD = "enable";
/* I3:   */   public static final String EACH_OTHER = "each_other";
/* I4:   */ }


/* Location:           C:\Yuya\Development\Genesis\genesis.jar
 * Qualified Name:     constants.Markers
 * JD-Core Version:    0.7.0.1
 */